version: '3.8'

services:
  app:
    build:
      context: .  # Build the Dockerfile from the current directory
    container_name: nestjs-app
    ports:
      - "3000:3000"  # Expose port 3000 for NestJS app
    environment:
      - MONGO_URI=mongodb://mongo:27017/sportsdb  # MongoDB connection URI
    depends_on:
      - mongo  # Ensure MongoDB is up before starting the app
    networks:
      - app-network
      
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"  # Exposing port 27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root  # Username for the root user
      - MONGO_INITDB_ROOT_PASSWORD=rootpassword  # Password for the root user
    volumes:
      - mongodb_data:/data/db  # Persistent storage for MongoDB data
    networks:
      - mongo-network
    restart: unless-stopped  # Restart the container unless explicitly stopped

volumes:
  mongodb_data:
    driver: local  # Ensures MongoDB data persists even after container restarts

networks:
  mongo-network:
    driver: bridge  # Using the bridge network driver to allow containers to communicate
